# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://wrlog.github.io/Wr.github.io/
date_format: "ordinal"
title: Hi,I'm Wen-Rui Tan,
subtitle: "Short Notes"
description: "Short Notes"
keywords: Wenrui
timezone: United State/Eastern Time Zone
encoding: "utf-8"
side_bar_repo_limit: 0

# ---------------- #
#      Author      #
# ---------------- #
author: WenRui
organization: 
organization_url: 
github_username: WenruiTan
location: United State
email: tan.wenrui213@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #

navs:
  -
    href: /
    label: Home

  -
    href: /categories/
    label: Category

#   -
#     href: /archives/
#     label: Archives

#   -
#     href: /open-source/
#     label: open-source

  -
    href: /wiki/
    label: Wiki
    
  -
    href: /about/
    label: About

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/
        
repository: https://wrlog.github.io/Wr.github.io/

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk, utterances, beaudar
comments_provider: gitment
# gitment 配置参考：https://imsun.net/posts/gitment-introduction/

disqus:
    username: 

gitment:
    owner: WenruiTan
    repo: blog-comments
    oauth:
        client_id: ce2239587a9dc9830236
        client_secret: 0eeeea7ac0249f02c36935ddfc995efea5572481
        
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#      Google      #
# ---------------- #
google:
    analytics_id:G-7WJEV91PM7
